mehta-lab/VisCy

pyproject.toml
=> Bump iohub version

README.md
Introducing capitalization to highlight vision and single-cell aspects of the pipeline.
=> viscy -> VisCy (#34)

README.md
=> Update readme.md typo for `cd VisCy`

viscy/light/data.py
Added docstrings for non-lightning datamodule methods and private functions.
For the complete batch-loading process, see [how hooks are called in pytorch lightning](https://lightning.ai/docs/pytorch/stable/data/datamodule.html). It is helpful for developers to familiarize themselves with the framework used, rather than trying to recreate the documentation.
Resolves #48.
=> Document data methods

viscy/scripts/visualize_features.py
Add script to visualize feature maps produced by deep layers with PCA and t-SNE.
=> Visualize feature maps

CITATION.cff, viscy/light/engine.py
Note that this PR does not set a version for the citation since we don't have a released version yet.
Authors: please check and edit your information.
=> Add CITATION.cff

pyproject.toml
=> bumping to cellpose 3

viscy/light/predict_writer.py
This PR fixes the bug for the scale_metadata to retrieve the scale metadata if the input is a Positions or Plate level.
=> Scale metadata handling for positions

README.md, pyproject.toml
Bump dependencies and update README installation guide.
=> Bump lightning and matplotlib

pyproject.toml
https://github.com/Project-MONAI/MONAI/issues/7856
Fix #110.
=> Pin numpy due to MONAI bug

README.md
This PR add a link to the demos for VS and the link to the library of models wiki.
TODO:
=> Adding link to demos and library of VS models wiki

.gitignore, applications/contrastive_phenotyping/demo_cli_fit.yml, applications/contrastive_phenotyping/demo_cli_fit_slurm.sh
Documenting how to use lighting CLI for contrastive learning.
=> version lighting CLI example

applications/contrastive_phenotyping/evaluation/grad_attr.py, applications/contrastive_phenotyping/evaluation/linear_probing.py, pyproject.toml, tests/representation/test_lca.py, viscy/data/triplet.py, viscy/representation/lca.py
~Refactored the linear classifier with lightning.~
Use logistic regression to optimize a linear classifier and copy the weights to torch linear layer (#169).
Fixed the bug where the dataset is not split: the dataset is now split manually by FOVs so that we can count infection percentage only in the test FOV.
Added a script to demonstrate usage.
Added a script to use the trained classifier for visualizing integrated gradients.
=> Linear probing

applications/contrastive_phenotyping/evaluation/figure.mplstyle, applications/contrastive_phenotyping/evaluation/grad_attr.py, applications/contrastive_phenotyping/figures/organelle_dynamics.py, pyproject.toml, viscy/representation/lca.py
Tweaked plotting of attribution.
@Soorya19Pradeep @alishbaimran I added a matplotlib style sheet that will produce the exact typeface and fontsize in latex for your reference. For a script in `applications/contrastive_phenotyping/evaluation`, it can be used with:
```py
plt.style.use("./figure.mplstyle")
```
=> Tweak attribution visualization

README.md
Center GIF and format markdown.
=> Center GIF

CITATION.cff
Add @alishbaimran to CITATION.cff.
=> Add new author to citation

README.md, pyproject.toml
Add badges for:
- PyPI stable version
- PyPI monthly downloads
- PyPI total downloads
- GitHub contributors
- GitHub stars
- GitHub forks
- SPEC 0 adoption (placeholder for supported python versions)
=> Add badges to readme

.github/workflows/pr.yml, CONTRIBUTING.md, pyproject.toml
Include all the optionals in the dev requirements.
=> Simplify development installation

pyproject.toml
Bump iohub (pending a stable release).
=> Bump iohub

examples/virtual_staining/vcp_tutorials/README.md, examples/virtual_staining/vcp_tutorials/hek293t.ipynb, examples/virtual_staining/vcp_tutorials/hek293t.py
Add tutorials for HEK293T cells and zebrafish neuromast with CLI inference and 3D visualization using stackview.
https://colab.research.google.com/github/mehta-lab/VisCy/blob/vcp-cli-tutorials/examples/virtual_staining/vcp_tutorials/hek293t.ipynb
=> Add CLI tutorials for VCP

examples/virtual_staining/vcp_tutorials/hek293t.ipynb, examples/virtual_staining/vcp_tutorials/hek293t.py, examples/virtual_staining/vcp_tutorials/quick_start.ipynb, examples/virtual_staining/vcp_tutorials/quick_start.py
- language edits in the HEK tutorial
- fix dependencies of the quick start
=> Update VCP tutorials

viscy/translation/engine.py
Cellpose 4 will print a message when it's imported and it's quite confusing in our tutorials:
```
Welcome to CellposeSAM, cellpose v4.0.1! The neural network component of
CPSAM is much larger than in previous versions and CPU excution is slow. 
We encourage users to use GPU/MPS if available.
```
Related: #231
=> Delay cellpose import

examples/virtual_staining/vcp_tutorials/hek293t.ipynb, examples/virtual_staining/vcp_tutorials/hek293t.py
Keeping the tutorial in sync with the VCP version.
Supersedes #247
=> Add contact information

tests/evaluation/test_evaluation_metrics.py, tests/translation/test_evaluation.py
Temporary patch for CI to workaround upstream problem.
=> Skip broken test with pycocotools on python 3.13

examples/virtual_staining/vcp_tutorials/hek293t.ipynb, examples/virtual_staining/vcp_tutorials/hek293t.py, examples/virtual_staining/vcp_tutorials/quick_start.ipynb, examples/virtual_staining/vcp_tutorials/quick_start.py
- Relax the patch version component so the latest in 0.3.x gets installed.
- Enhance visualization contrast in the HEK293T tutorial.
=> Tweak VCP tutorials

examples/DynaCLR/README.md, examples/DynaCLR/examples_cli/dynaclr_microglia_onnx.yml, viscy/data/hcs.py, viscy/data/triplet.py, viscy/representation/engine.py, viscy/utils/slurm_utils.py
This PR modifies the forward method to generat the features and projections.  
This change maintains compatibility with the existing contrastive learning pipeline while also making the encoder features accessible for other uses. The contrastive loss is still computed on the projections, but you now have access to the full feature representation when needed.
=> ONNX support for DynaCLR

viscy/translation/engine.py
=> Document AugmentedPredictionVSUNet

viscy/representation/evaluation/feature.py
=> Fix deprecated numpy call

tests/data/test_triplet.py, viscy/data/triplet.py
Allows for spatial augmentation along Z in non-time-aware sampling.
=> Expose Final Z cropping in TripletDataModule

viscy/data/cell_classification.py, viscy/data/typing.py
This PR takes a first stab at standardizing the labels and annotation columns for our datasets with the hope to merge annotations across datasets easily.
=> Adding annotation typings

viscy/scripts/affine_shear_3dphatom_demo.py
Example to visualize the shearing transform. It was hard for me to see what the batch transform was doing so I wrote something to convince myself.
=> Example for Shearing transform

viscy/data/combined.py
PR rebased to main add the patch to run model summary. 
Closed #304 because it was easier to just cherry pick from here.
=> Patch ModelSummary with BatchTransforms

pyproject.toml
=> Pin lightning for 0.3
