README.md, pyproject.toml, viscy/light/engine.py
@ziw-liu improving the accuracy of README and dependencies. cellpose is imported by viscy.light.engine, so I moved from metrics to main dependencies. Please adjust if the import is an accident.
=> readme + dependencies tested with python 3.10

README.md, examples/demo_dlmbl/python/excercise_1.py, pyproject.toml, viscy/light/engine.py
=> Demo notebooks

viscy/light/data.py
Fix slicing and worker spawning in the data module
=> Fix datamodule

README.md
Introducing capitalization to highlight vision and single-cell aspects of the pipeline.
=> viscy -> VisCy

viscy/cli/cli.py, viscy/light/data.py, viscy/light/engine.py, viscy/scripts/network_diagram.py
@mattersoflight and I had a discussion about potential data utilization problem when only sampling one patch from a stack at each training step. While with longer training schedule, all ROIs will still get sampled, this does waste a lot of I/O bandwidth, since most of the data loaded from disk is not used in the batch. This problem becomes more prominent when the stack depth increases, where even local NVME pools cannot keep the GPU fed with data.
This PR implements a new data module argument `train_patches_per_stack`, allowing sampling multiple patches from a single stack, effective only in training. The batch size has to be divisible by this number for collation to work. When I/O-bound, this can greatly speed up data-loading. Below is a test of single-precision batch tensor with size …
=> Allow sampling multiple patches from the same stack

viscy/light/engine.py
Fix the center slice index for 3D output when computing metrics.
=> Fix center slice metrics for 3D output

examples/configs/fit_example.yml, examples/configs/predict_example.yml, viscy/light/engine.py
=> Configure the number of  image samples logged at each epoch and batch

docs/usage.md, examples/configs/export_example.yml, examples/configs/predict_example.yml, examples/configs/test_example.yml
Adds a short description of the virtual staining workflow in its current state.
=> Example workflow

docs/logo/viscy.svg
This is a proposal to create a icon for the project.
@mattersoflight and I had an offline discussion. Some ideas were:
- encode-decoder architecture
- images of cells undergoing transforms
Here I'm materializing these ideas in a very simple (and rudimentary) form. Also trying to adhere to the Biohub style guide (with colors and the usage of line-connected circles). This first draft features:
- encode-decoder schematic
- circular structures resembling (very abstract) cellular compartments
- subsets of the connecting lines can form characters in the project name (with some imagination of a Phoenician font)
Created with Inkscape. Suggestions and edits are welcome!
Some rendered theme variants (light, dark, cyan):
=> Project icon

viscy/light/predict_writer.py
Open `HCSPredictionWriter.plate` after appending new channels so that the new channels are visible when retrieving channel indices.
=> Fix predicting new channels in an existing store

.github/workflows/pr.yml, CONTRIBUTING.md, README.md, examples/demo_dlmbl/setup.sh, pyproject.toml, viscy/evaluation/evaluation_metrics.py
Replaced lapsolver with scipy, allowing support for python 3.11.
Updated iohub and dropped python 3.9, now testing on 3.10 and 3.11.
Moved visualization dependencies into optional.
Updated documentation to add reference to the Mantis preprint. Closes #63.
=> Bump dependencies and update documentation

examples/configs/fit_example.yml, viscy/light/engine.py
This PR adds the an extra parameter for the CLI to provide the checkpoint path to be loaded such that is compatible when using warmup cosine learning rates. By default, the lightning CLI has a `ckpt_path`, but this loads the previous checkpoint's learning rate as well as the weights. When using the latter option, the re-training for next model starts as a 'sine' function rather than cosine.
=> checkpoint as a model config parameter for warmup cosine learning rates

viscy/evaluation/evaluation_metrics.py
Fix overcounting instances when the label values are not contiguous.
=> Filter empty detections in labels

viscy/light/engine.py, viscy/scripts/network_diagram.py, viscy/unet/networks/Unet21D.py, viscy/unet/networks/Unet22D.py, viscy/unet/networks/fcmae.py
Removed the "2.1D" architecture and made the output stack depth of "2.2D" configurable between 2D and 3D.
Fix #78.
=> Fix 3D to 2D prediction with UNeXt2 model

examples/configs/predict_example.yml, viscy/light/predict_writer.py
PR adds the scale metadata to the output stores. 
~This is solution requires one to add an input_metadata_store that has the proper scale.~
=> Add the scale metadata to the output_stores

examples/demos/demo_vscyto2d.py, examples/demos/demo_vscyto3d.py, examples/demos/demo_vsneuromast.py, viscy/data/hcs.py, viscy/data/typing.py
Fixed the issue of normalization statistics (`float` from JSON) being auto-casted to `torch.float64` so that MPS works on macos_arm64.
Also disabled multiprocessing. Or we can put the whole thing in a `if __name__ == '__main__':` guard.
=> Fix demos on other platforms

applications/contrastive_phenotyping/training_script.py, applications/contrastive_phenotyping/training_script_resnet.py, viscy/representation/contrastive.py, viscy/unet/networks/resnet.py
- initialize resnet50 using timm  (the classical resent50 matches best with dynacontrast's resnet50)
- recycled the stem from convnext
- replaced fc with projection head, see viscy/representation/contrastive.py
Here is a side-by-side comparison of the model view, the timm-resnet50 model is close-enough compared with dynacontrast-resnet50.  Therefore we can use the resnet50 to approximate a model baseline that matches dynacontrast
=> add resnet50 to ContrastiveEncoder

viscy/data/ctmc_v1.py, viscy/data/hcs.py, viscy/light/engine.py, viscy/light/predict_writer.py, viscy/utils/image_utils.py
This PR adds the test time augmentations to the prediction steps.
These are currently hardcoded to be rotations of (0,90,180 and 270 deg) by setting the `trainer.test_time_augmentation=True`
Ideally, we want this to be added during training the paper suggests so that we are rotationally invariant.
=> Test time augmentations

viscy/applications/contrastive_phenotyping/graphs_ConvNeXt_ResNet.py, viscy/applications/contrastive_phenotyping/predict.py, viscy/data/hcs.py, viscy/light/engine.py, viscy/representation/contrastive.py, viscy/unet/networks/unext2.py
* Common stem for convnext and resnet. 
* Model made up of stem, encoder, and projection sub-graphs. Easier to compute embedding and projection.
* Retain layernorm in the stem. 
* stem implements 4x downsampling.
* output both projections and embedding.
=> fixed the stem and forward pass

applications/contrastive_phenotyping/demo_fit.py, tests/preprocessing/test_pixel_ratio.py, viscy/data/hcs.py, viscy/light/engine.py
Fix #116.
Example logs:
```sh
/hpc/projects/intracellular_dashboard/viral-sensor/infection_classification/models/test_tb
```
=> Migrate from wandb to tensorboard

viscy/cli/contrastive_triplet.py, viscy/data/triplet.py, viscy/transforms.py
A simple CLI is added for training contrastive models with triplet data (not accessible from the main `viscy` entry point and not working for all stages). This allows hyperparameters to be documented in human-readable YAML config files along side TensorBoard training logs.
Usage:
```sh
python -m viscy.cli.contrastive_triplet fit -c fit.yml
```
Example training run:
```sh
/hpc/projects/intracellular_dashboard/viral-sensor/infection_classification/models/contrastive_tune_augmentations
```
For the future iteration (v0.3?) it might make sense to replace the manual CLI entry point (`viscy [command]`) with python's built-in (`python -m viscy.cli.module [command]`) to make supporting multiple learning tasks easier.
=> Tune augmentations with CLI and config for contrastive models

viscy/light/engine.py, viscy/representation/contrastive.py
Make `drop_path_rate` configurable in `ContrastiveEncoder` and `ContrastiveModule`. This value was previously hard-coded to be `0.2` for all models (ConvNeXt and ResNet), while `timm`'s default is `0.0`.
=> Configurable drop path rate in contrastive models

applications/contrastive_phenotyping/contrastive_cli/plot_embeddings.py
Add animation to the interactive scatter plot to show tracks moving in latent space.
=> Animated latent space

applications/contrastive_phenotyping/contrastive_cli/plot_embeddings.py
This PR aims to add plotting utilities to visualize features (or their dimensionally reduced versions) over tracks of single cells, alongside images of the same tracked cell.
=> Plot tracks in latent space and real space

viscy/light/engine.py
`torch.cuda.amp.custom_fwd()` is deprecated in favor of `torch.amp.custom_fwd()`.
=> Fix deprecated custom forward method

viscy/scripts/effective_receptive_field.py
Add a script to visualize effective receptive field using point response in back propagation.
A vanilla U-Net after initialization:
UNeXt2 (2D) after initialization:
Trained CytoVS2D:
=> Add script to visualize effective receptive field

applications/contrastive_phenotyping/contrastive_cli/fit_ctc_mps.yml, applications/contrastive_phenotyping/contrastive_cli/predict_ctc_mps.yml, viscy/data/triplet.py
Sampling strategy for triplet contrastive learning is now configured with `viscy.data.triplet.TripletDataModule(time_interval=...)`.
1. `time_interval == "any"`
Same as before this PR. The positive sample is the augmented version of the anchor, and the negative sample is any other patch from a different track.
If each node (`id`) in the tracking result is assigned a different `track_id`, this reduces to the classical patch-wise contrastive learning without tracking information.
2. `isinstance(time_interval, int) == True`
For time interval $\tau$, the positive sample of anchor at time point $t$ is sampled from the same track at time point $t + \tau$, and the negative example is sampled from a different track also at time point $t + \tau$. Example log from CTC's DIC-D2DH-HeLa dataset …
=> Sample positive and negative samples with a time offset for the triplet contrastive task

applications/contrastive_phenotyping/evaluation/grad_attr.py, applications/contrastive_phenotyping/evaluation/linear_probing.py, pyproject.toml, tests/representation/test_lca.py, viscy/representation/lca.py
Optimizing the logistic regression model in sklearn (max-entropy) is the exact same function and objective as optimizing a linear layer with cross-entropy-with-logit loss in torch. The only differences are least-squares vs SGD, and weight regularization. Therefore, by copying the weights and bias from a sklearn model to a torch linear layer, we can use the same deterministic optimization for evaluating classification performance and model interpretation methods that require gradients.
I also include a test case to verify the above: the logits produced by the sklearn and torch models are almost equal (with relative tolerance 0.001).
=> Use sklearn's logistic regression for linear probing

pyproject.toml, viscy/data/hcs_ram.py
need to update torch>2.4.1  for #151 to be effective. 
Otherwise you get the error:
```
@torch.amp.custom_fwd(device_type="cuda", cast_inputs=torch.float32)
AttributeError: module 'torch.amp' has no attribute 'custom_fwd'
```
=> Bump torch to 2.4.1

viscy/representation/embedding_writer.py, viscy/representation/engine.py, viscy/representation/evalutation/dimensionality_reduction.py
Store 2-component UMAP in the prediction Zarr store of `viscy.representation.embedding_writer.EmbeddingWriter`. This is intended to be loaded by the [napari widget](https://github.com/czbiohub-sf/napari-iohub/pull/13) for plotting.
Close #166.
=> Store UMAP embeddings in SSL predictions

tests/translation/test_predict_writer.py, viscy/translation/predict_writer.py
=> Vendor pad shape function

pyproject.toml
MONAI 1.4.0 adds support for NumPy>2.
=> Bump MONAI to unpin NumPy

viscy/data/combined.py, viscy/data/ctmc_v1.py, viscy/data/gpu_aug.py, viscy/data/livecell.py, viscy/data/typing.py, viscy/transforms.py, viscy/translation/engine.py
Building on top of #196:
Doing non-trivial augmentations on large imaging volumes has become a bottleneck in training image translation models. By keeping the initial cropping and normalization on the CPU workers, while executing the more heavy transforms (especially the resampling ones) on the GPU, training can be significantly faster.
For 2D FCMAE, reaching the same validation loss is ~7x the speed compared to v0.2. Compare these logs:
```
/hpc/projects/comp.micro/virtual_staining/models/hek-a549-bj5a-20x/lightning_logs/tiny-2x2-fcmae-amp-hek-a549-bj5a-400ep
/hpc/projects/comp.micro/virtual_staining/models/fcmae-2d/test-logs/hek-a549-bj5a-gpu-aug-val-every-10
```
And for 3D FCMAE, the total voxel throughput is ~3x of v0.2, potentially limited by CPU-GPU transfer.
~Caveat: since the …
=> GPU transform for FCMAE pre-training

viscy/data/hcs.py
This is the temporary fix to the memory leak we observe in #201
=> Expose prefetch_factor and persistent_worker for the HCS datamodule

tests/data/test_data.py, viscy/data/hcs.py
Replace the `architecture` argument with explicit `targe_2d` to avoid confusion. Also changed the default to `False` since 2.5D is no longer used in production.
Previously, if `architecture` is not specified, it will default to '2.5D' and produce incorrect results for 3D models, where the output would have 1 Z-window worth of extra blank slices relative to the input. This was not a problem before #182, when this argument was hard-linked by the CLI with the model configuration.
@tayllatheodoro @Soorya19Pradeep @ieivanov @talonchandler:
This parameter used to be automatically configured (correctly) for `viscy<=0.2.1`, which is all the stable versions on PyPI. If you recently did 3D predictions with a pre-release installation, please check the results to make sure that the configuration is …
=> Explicit target shape argument in the HCS data module

applications/contrastive_phenotyping/evaluation/time_decay_knn.py, viscy/representation/evaluation/clustering.py
An ideal cell state representation has the following properties:
- When the cell state does not change, the neighboring time points of the same cell should have more similar embeddings compared to other cells (continuity)
- When the cell state does change, the embeddings change a lot so that different cell states can be expressed (dynamic range)
We observed these properties for time-regularized models visually in UMAPs. However, Euclidean distances in UMAP space carry no global meaning, so the observations cannot be directly quantified by comparing UMAP values. This PR provides methods to describe the embedding similarities close to how UMAP is computed: each sample is ranked as the $k$-th nearest neighbor for each sample, and the displacement in this neighborhood ($k$ at $t_{i+1}$ for …
=> Rank nearest neighbors in embedding space

applications/contrastive_phenotyping/evaluation/ALFI_displacement.py, applications/contrastive_phenotyping/evaluation/cosine_dissimilarity_dataset.py, applications/contrastive_phenotyping/evaluation/time_decay_knn.py, applications/contrastive_phenotyping/examples_cli/predict.yml, pyproject.toml, viscy/data/hcs.py, viscy/data/triplet.py, viscy/representation/embedding_writer.py, viscy/representation/engine.py, viscy/representation/evaluation/clustering.py, viscy/representation/evaluation/dimensionality_reduction.py, viscy/representation/evaluation/distance.py, viscy/scripts/recompute_phate.py
- Adding the ntxent loss besides the tripletmarginal loss
=> Adding NTXENT loss

applications/contrastive_phenotyping/evaluation/cosine_dissimilarity_dataset.py
@Soorya19Pradeep could you review this and merge if it runs for you? I ran it myself without problems.
```
Adjacent Frame Dissimilarity Statistics:
Mean:           0.149
Std:            0.183
Median:         0.070
Peak:           0.035
P1:             0.054
P99:            0.425
Random Sampling Statistics:
Mean:           0.992
Std:            0.400
Median:         1.056
Peak:           1.385
Comparison Metrics:
Dynamic Range:  1.350
Distribution Sizes:
Adjacent Frame: 11,644 samples
Random:         11,644 samples
```
=> Fix the wrong import name for pairwise_distance_matrix()

viscy/data/triplet.py
We forgot to change the TripletDataModule() after the HCSDatamodule() merged changes in #212
=> Fixing the TripletDataModule() after changes to HCSDataModule

viscy/data/triplet.py
This PR fixes #224. 
- Added relevant doctrings
- Exposed variable in `TripletDataModule` so that it can configure the `TripletDataset` for `fit`.
=> Expose the option to not return negative samples in the triplet data module

applications/contrastive_phenotyping/evaluation/imagenet_pretrained_features.py, viscy/representation/evaluation/__init__.py
Use ImageNet-pretrained encoder from timm as feature extractor.
For example, the PCA of the features (ALFI test split) shows separation between FOVs:
=> Script to use ConvNeXt v1 Tiny as a feature extractor

viscy/data/hcs.py
Provide a better error message when the requested Z window size is larger than the image array.
=> Check if the sliding window size is valid

.github/workflows/pr.yml, CONTRIBUTING.md, examples/virtual_staining/dlmbl_exercise/prepare-exercise.sh, examples/virtual_staining/dlmbl_exercise/setup.sh, examples/virtual_staining/img2img_translation/prepare-exercise.sh, examples/virtual_staining/img2img_translation/setup.sh, examples/virtual_staining/phase_contrast/prepare-exercise.sh, examples/virtual_staining/phase_contrast/setup.sh, pyproject.toml, tests/unet/networks/Unet25D_tests.py, tests/unet/networks/Unet2D_tests.py, tests/unet/networks/layers/ConvBlock2D_tests.py, tests/unet/networks/layers/ConvBlock3D_tests.py, viscy/representation/evaluation/dimensionality_reduction.py, viscy/scripts/profile_dataloader.py, viscy/scripts/visualize_features.py, viscy/unet/networks/Unet25D.py, viscy/unet/networks/Unet2D.py, viscy/utils/cli_utils.py, viscy/utils/logging.py, viscy/utils/mp_utils.py
One less dependency.
Changed instructions for examples, but didn't apply to source files to avoid conflict with #240.
=> Replace black with ruff

viscy/cli.py
A stop gap for #291 as suggested in https://github.com/Lightning-AI/pytorch-lightning/issues/21255#issuecomment-3350031132 (option 1).
=> Catch hyperparameter incompatibility in checkpoints
